// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// Notify provides a mock function with given fields: data
func (_m *Observer) Notify(data interface{}) {
	_m.Called(data)
}
