// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// PageController is an autogenerated mock type for the PageController type
type PageController struct {
	mock.Mock
}

// AddPage provides a mock function with given fields: w, r
func (_m *PageController) AddPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeletePage provides a mock function with given fields: w, r
func (_m *PageController) DeletePage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// EditPage provides a mock function with given fields: w, r
func (_m *PageController) EditPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllPages provides a mock function with given fields: w, r
func (_m *PageController) GetAllPages(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// PageExists provides a mock function with given fields: w, r
func (_m *PageController) PageExists(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ValidatePage provides a mock function with given fields: w, r
func (_m *PageController) ValidatePage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
