// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "github.com/manicar2093/web-monitor/db/entities"
	mock "github.com/stretchr/testify/mock"
)

// PhraseService is an autogenerated mock type for the PhraseService type
type PhraseService struct {
	mock.Mock
}

// AddPhrase provides a mock function with given fields: phrase
func (_m *PhraseService) AddPhrase(phrase entities.Phrase) error {
	ret := _m.Called(phrase)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Phrase) error); ok {
		r0 = rf(phrase)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
