// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// PhraseController is an autogenerated mock type for the PhraseController type
type PhraseController struct {
	mock.Mock
}

// AddPhrase provides a mock function with given fields: w, r
func (_m *PhraseController) AddPhrase(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeletePhrase provides a mock function with given fields: w, r
func (_m *PhraseController) DeletePhrase(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// EditPhrase provides a mock function with given fields: w, r
func (_m *PhraseController) EditPhrase(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllPhrases provides a mock function with given fields: w, r
func (_m *PhraseController) GetAllPhrases(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
