// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReadFunc is an autogenerated mock type for the ReadFunc type
type ReadFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: data
func (_m *ReadFunc) Execute(data string) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
