// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TemplateController is an autogenerated mock type for the TemplateController type
type TemplateController struct {
	mock.Mock
}

// IndexPage provides a mock function with given fields: w, r
func (_m *TemplateController) IndexPage(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
