// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TemplateService is an autogenerated mock type for the TemplateService type
type TemplateService struct {
	mock.Mock
}

// Render provides a mock function with given fields: w, templateName, content
func (_m *TemplateService) Render(w http.ResponseWriter, templateName string, content interface{}) error {
	ret := _m.Called(w, templateName, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, string, interface{}) error); ok {
		r0 = rf(w, templateName, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
