// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidatorService is an autogenerated mock type for the ValidatorService type
type ValidatorService struct {
	mock.Mock
}

// ValidatePages provides a mock function with given fields:
func (_m *ValidatorService) ValidatePages() {
	_m.Called()
}
