// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "github.com/manicar2093/web-monitor/entities"
	mock "github.com/stretchr/testify/mock"

	models "github.com/manicar2093/web-monitor/models"
)

// ValidatorService is an autogenerated mock type for the ValidatorService type
type ValidatorService struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *ValidatorService) Start() {
	_m.Called()
}

// ValidatePage provides a mock function with given fields: page, isInstant
func (_m *ValidatorService) ValidatePage(page *entities.Page, isInstant bool) (models.Notification, bool) {
	ret := _m.Called(page, isInstant)

	var r0 models.Notification
	if rf, ok := ret.Get(0).(func(*entities.Page, bool) models.Notification); ok {
		r0 = rf(page, isInstant)
	} else {
		r0 = ret.Get(0).(models.Notification)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*entities.Page, bool) bool); ok {
		r1 = rf(page, isInstant)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
